-- test_items Data
-- Auto-generated by Excel Converter

return {
    [1001] = {
        ID = 1001,
        Name = "测试剑",
        Attributes = {Attack = 100, Defense = 50}
    },
    [1002] = {
        ID = 1002,
        Name = "测试盾",
        Attributes = {Attack = 10, Defense = 200}
    },
    [1003] = {
        ID = 1003,
        Name = "测试药水",
        Attributes = {Attack = 0, Defense = 0}
    }
} 